### ISSUE TITLE
spaties

### ISSUE THREAD

**Issue by TimOosterveer** [RukiyaTossou/the-client-website#3]
https://github.com/RukiyaTossou/the-client-website/blob/daeb06a2168fc6beba80e90ac134d1800359f300/index.html#L153

Je beter alles in een li onder elkaar zetten, is netter.

**Comment by RukiyaTossou** [comment]
![image](https://github.com/RukiyaTossou/the-client-website/assets/114156045/a538896f-eaf1-4b10-acf6-a126ed7e626a)
