### ISSUE TITLE
Spaties tussen elementen

### ISSUE THREAD

**Issue by TimOosterveer** [RukiyaTossou/the-client-website#5]
https://github.com/RukiyaTossou/the-client-website/blob/daeb06a2168fc6beba80e90ac134d1800359f300/index.html#L151

**Comment by RukiyaTossou** [comment]
![image](https://github.com/RukiyaTossou/the-client-website/assets/114156045/38faba4b-4aa1-4bb3-87bf-8515e36fff34)
